--SELECT  title, description FROM film;
--SELECT * FROM film 
--WHERE length >60 and length <75 ;
--WHERE rental_rate = 0.99 and replacement_cost = 12.99 or replacement_cost = 28.99;
--SELECT * FROM customer
--where first_name = 'Mary';
--SELECT * FROM film
--WHERE  NOT(NOT ( rental_rate = 4.99 or rental_rate = 2.99)) ;
--SELECT * FROM film
--WHERE not length > 50 ;
